ricerca: ricerca.c Makefile
	gcc -ansi -Wall -O ricerca.c -o ricerca

ordina: sorts.c Makefile
	gcc -ansi -Wall -O sorts.c -o ordina

pulisci:
	rm -f ricerca.o

pulisci_tutto:
	rm -f ricerca ricerca.o