coda_stringhe_rand: coda_stringhe_rand.c Makefile
	gcc -ansi -Wall -O coda_stringhe_rand.c -o coda_stringhe_rand

pulisci:
	rm -f coda_stringhe_rand

pulisci_tutto:
	rm -f coda_stringhe_rand coda_stringhe_rand.o